_base_:
  - ../_base_/igxl_s2git1m_ep100_mmdit_encdec.yaml
  - ../../../../datasets/raev2/stage3/spacenet6/train.yaml
  - ../../../../eval/train/stage3_spacenet6_256.yaml

dataset:
  fixed_label: 9

inference:
  sample_dir: experiments/raev2/stage3/spacenet6
  save_folder: igxl_s2git1m_ep100_mmdit_encdec_ep80
