data:
  name: QXSLAB_SAROPT
  default_path: dataset/QXSLAB_SAROPT

dataset:
  type: Dataset_RAEPairedI2I
  dataroot: dataset/QXSLAB_SAROPT
  pipeline_dir: raev2/stage3/qxslab_saropt
  split: train
  source_dir: sar
  target_dir: opt
  is_train: true
  fixed_label: 0

train_pipeline:
  - {type: CenterCropArr, keys: [img, img_ref], size: 256}
  - {type: RandomFlip, keys: [img, img_ref], prob: 0.5, direction: horizontal}
  - {type: ToTensor, keys: [img, img_ref]}
